---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      GITHUB_ACTIONS: true
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.OAPICF_GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - uses: iamsauravsharma/create-dotenv@v4.0.0
        with:
          file-path: '/tmp/.env'
      - run: echo "Env file content:"
      - run: cat /tmp/.env
      - uses: cliffano/command-docker-action@v1.4.0
        with:
          command: 'make ci'
          image: cliffano/studio:2.16.0
          shell: bash
          extra_path: /usr/local/go/bin:/usr/local/maven/bin:/usr/local/node/bin:/usr/local/openjdk-jdk/bin:/root/.cargo/bin:/root/go/bin
          env_file: '/tmp/.env'
      - run: npm install -g gh-pages
      - run: CACHE_DIR=/tmp gh-pages --dist doc/ --user "pakkunbot <blah+pakkun@cliffano.com>" --repo "https://cliffano:${{ secrets.OAPICF_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
